# Examine footprint summary

In [1]:
import geopandas as gpd
import pandas as pd

/explore/nobackup/people/pmontesa/.nccstmp/ipykernel_3773223/1565847299.py:1: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd

#### Read the latest footprint

In [2]:
footprint_gdf_acquisitions_sites = gpd.read_file('/explore/nobackup/projects/CSDA_eval/footprints/footprints_CSDA_eval_ACQUISITIONS_latest.gpkg')

/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)
/panfs/ccds02/app/modules/jupyter/ilab/tensorflow-kernel/lib/python3.8/site-packages/pyproj/../../.././libtiff.so.6: version `LIBTIFF_4.6.1' not found (required by /app/jupyter/ilab/jupyter-lab/prod/lib/gdalplugins/../libgdal.so.36)

In [3]:
footprint_gdf_acquisitions_sites[
    (footprint_gdf_acquisitions_sites.Site_Primary == 'Baotou') &
    (footprint_gdf_acquisitions_sites.affiliation == 'Airbus') &
    (footprint_gdf_acquisitions_sites.image_type == 'MS')
].path.to_list()

['/explore/nobackup/projects/CSDA_eval/Airbus/PROD_SPOT6_001/VOL_SPOT6_001_A/IMG_SPOT6_MS_001_A']

In [4]:
footprint_gdf_acquisitions_sites[
    (footprint_gdf_acquisitions_sites.Site_Primary == 'PICS Libya-4') &
    (footprint_gdf_acquisitions_sites.affiliation == 'Airbus') &
    (footprint_gdf_acquisitions_sites.image_type == 'MS')
].path.to_list()

['/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25033039-2-01_DS_PHR1A_202508220911321_FR1_PX_E023N28_0514_01816/7513397101/IMG_PHR1A_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25033039-5-01_DS_PHR1A_202509030918474_FR1_PX_E023N28_0514_01804/7521001101/IMG_PHR1A_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25033039-7-01_DS_PHR1A_202509100915098_FR1_PX_E023N28_0514_01816/7528020101/IMG_PHR1A_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25037632-2-01_DS_PHR1A_202509170911251_FR1_PX_E023N28_0514_01816/7542280101/IMG_PHR1A_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25033039-3-01_DS_PHR1B_202508210918461_FR1_PX_E023N28_0514_01804/7513426101/IMG_PHR1B_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25033039-4-01_DS_PHR1B_202508280915061_FR1_PX_E023N28_0514_01816/7515454101/IMG_PHR1B_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25033039-6-01_DS_PHR1B_202509040911169_FR1_PX_E023N28_0514_02147/7523161101/IMG_PHR1B_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/Pleiades/pics-libya-4/PICS_Libya_4_Libya_PHR_SO25037633-2-01_DS_PHR1B_202509160918349_FR1_PX_E023N28_0514_01804/7542281101/IMG_PHR1B_MS_002',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/wo-acq/WO_000404701_1_2_SAL25380146-2_ACQ_PNEO3_06125201861942/000404701_1_2_STD_A/IMG_01_PNEO3_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/libya-4/Libya_4_Libya_PNEO_SAL25385581/000410165_1_2_STD_A/IMG_01_PNEO3_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/libya-4/Libya_4_Libya_PNEO_SAL25391255/000416025_1_2_STD_A/IMG_01_PNEO3_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/libya-4/Libya_4_Libya_PNEO3_SAL25401451/000426693_1_1_STD_A/IMG_01_PNEO3_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/wo-acq/WO_000410164_1_2_SAL25385582-2_ACQ_PNEO4_06117802002034/000410164_1_2_STD_A/IMG_01_PNEO4_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/wo-acq/WO_000410164_1_3_SAL25385582-3_ACQ_PNEO4_06117802002035/000410164_1_3_STD_A/IMG_01_PNEO4_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/libya-4/Libya_4_Libya_PNEO_SAL25387088/000411383_1_2_STD_A/IMG_01_PNEO4_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/libya-4/Libya_4_Libya_PNEO4_SAL25398131/000423275_1_1_STD_A/IMG_01_PNEO4_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/PleiadesNeo/libya-4/Libya_4_Libya_PNEO4_SAL25406869/000432307_1_1_STD_A/IMG_01_PNEO4_MS-FS',
 '/explore/nobackup/projects/CSDA_eval/Airbus/SPOT/libya-4/PROD_SPOT6_001/VOL_SPOT6_001_A/IMG_SPOT6_MS_001_A, /explore/nobackup/projects/CSDA_eval/Airbus/SPOT/libya-4/Libya_4_Libya_SPOT_SO25033062-2-01_DS_SPOT6_202508090844524_FR1_FR1_SV1_SV1_E023N29_01871/PROD_SPOT6_001/VOL_SPOT6_001_A/IMG_SPOT6_MS_001_A',
 '/explore/nobackup/projects/CSDA_eval/Airbus/SPOT/libya-4/Libya_4_Libya_SPOT_SO25033062-3-01_DS_SPOT6_202508160841036_FR1_FR1_FR1_FR1_E023N29_01871/PROD_SPOT6_001/VOL_SPOT6_001_A/IMG_SPOT6_MS_001_A',
 '/explore/nobackup/projects/CSDA_eval/Airbus/SPOT/libya-4/Libya_4_Libya_SPOT_SO25033062-4-01_DS_SPOT6_202508280848265_FR1_FR1_FR1_FR1_E023N29_01871/PROD_SPOT6_001/VOL_SPOT6_001_A/IMG_SPOT6_MS_001_A']

#### Read footprint summary

In [11]:
final_summary = pd.read_csv('/explore/nobackup/projects/CSDA_eval/summaries/CSDA_eval_sites_footprint_summary_MS_latest.csv')

In [14]:
tmp_smry = final_summary\
.groupby(['affiliation', 'constellation','Site_Primary','sensor'])['acquisition_count','Acquisitions Requested','Acquisitions Remaining'].sum().reset_index()

tmp_smry[ (tmp_smry.Site_Primary == 'Baotou') & (tmp_smry.affiliation == 'Airbus')]

/explore/nobackup/people/pmontesa/.nccstmp/ipykernel_3773223/2121603522.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  tmp_smry = final_summary\

,affiliation,constellation,Site_Primary,sensor,acquisition_count,Acquisitions Requested,Acquisitions Remaining
42,Airbus,SPOT,Baotou,SPOT6,1,0,0

In [13]:
tmp_smry = final_summary\
.groupby(['affiliation', 'constellation','Site_Primary','sensor'])['acquisition_count','Acquisitions Requested','Acquisitions Remaining'].sum().reset_index()\
.sort_values(by='Acquisitions Remaining', ascending=False)

tmp_smry[ (tmp_smry.Site_Primary == 'PICS Libya-4') & (tmp_smry.affiliation == 'Airbus')]

/explore/nobackup/people/pmontesa/.nccstmp/ipykernel_3773223/1660397448.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  tmp_smry = final_summary\

,affiliation,constellation,Site_Primary,sensor,acquisition_count,Acquisitions Requested,Acquisitions Remaining
34,Airbus,Pleiades Neo,PICS Libya-4,PNEO4,5,4,0
33,Airbus,Pleiades Neo,PICS Libya-4,PNEO3,4,4,0
15,Airbus,Pleiades,PICS Libya-4,PHR1B,4,4,0
14,Airbus,Pleiades,PICS Libya-4,PHR1A,4,4,0
47,Airbus,SPOT,PICS Libya-4,SPOT6,3,3,0